Player.create!([
  {firstname: "Jung", name: "Impact", lastname: "Eon-yeong"},
  {firstname: "William", name: "Meteos", lastname: "Hartman"},
  {firstname: "Nicolaj", name: "Jensen", lastname: "Jensen"},
  {firstname: "Zachary", name: "Sneaky", lastname: "Scuderi"},
  {firstname: "Andy", name: "Smoothie", lastname: "Ta"},
  {firstname: "Bok", name: "Reapered", lastname: "Hang-gyu"},
  {firstname: "An", name: "Balls", lastname: "Le"},
  {firstname: "Hai", name: "Hai", lastname: "Lam"},
  {firstname: "Johnny", name: "Altec", lastname: "Ru"},
  {firstname: "Daerek", name: "LemonNation", lastname: "Hart"},
  {firstname: "Darshan", name: "Darshan", lastname: "Upadhyaha"},
  {firstname: "Jake", name: "Xmithie", lastname: "Puchero"},
  {firstname: "Choi", name: "Huhi", lastname: "Jae-hyun"},
  {firstname: "Trevor", name: "Stixxay", lastname: "Hayes"},
  {firstname: "Zaqueri", name: "aphromoo", lastname: "Black"},
  {firstname: "Tony", name: "Zikz", lastname: "Gray"},
  {firstname: "Jang", name: "Looper", lastname: "Hyeong-seok"},
  {firstname: "Henrik", name: "Froggen", lastname: "Hansen"},
  {firstname: "Yuri", name: "Keith", lastname: "Jew"},
  {firstname: "Simon", name: "Heaventime", lastname: "Jeon"},
  {firstname: "Lee", name: "Flame", lastname: "Ho-jong"},
  {firstname: "Joshua", name: "Dardoch", lastname: "Hartnett"},
  {firstname: "Eugene", name: "Pobelter", lastname: "Park"},
  {firstname: "Cody", name: "Cody Sun", lastname: "Sun"},
  {firstname: "David", name: "Hermes", lastname: "Tu"},
  {firstname: "Derek", name: "zig", lastname: "Shao"},
  {firstname: "Rami ", name: "Inori", lastname: "Charagh"},
  {firstname: "Yoo", name: "Ryu", lastname: "Sang-wook"},
  {firstname: "Noh", name: "Arrow", lastname: "Dong-hyeon"},
  {firstname: "Adrian", name: "Adrian", lastname: "Ma"},
  {firstname: "Kim", name: "Fly", lastname: "Sang-chui"},
  {firstname: "Jang", name: "Keane", lastname: "Lae-young"},
  {firstname: "Apollo", name: "Apollo", lastname: "Price"},
  {firstname: "Alex", name: "Xpecial", lastname: "Chu"},
  {firstname: "Shin", name: "Seraph", lastname: "Woo-yeong"},
  {firstname: "Kim", name: "Proxcin", lastname: "Se-young"},
  {firstname: "Noh", name: "Ninja", lastname: "Geon-woo"},
  {firstname: "Benjamin", name: "LOD", lastname: "deMunck"},
  {firstname: "Nickolas", name: "Hakuho", lastname: "Surgent"},
  {firstname: "Lee", name: "Miracle", lastname: "Hyeon-beom"},
  {firstname: "Samson", name: "Lourlo", lastname: "Jackson"},
  {firstname: "Greyson", name: "Goldenglue", lastname: "Gilmer"},
  {firstname: "Matthew", name: "Matt", lastname: "Elento"},
  {firstname: "David ", name: "DLim", lastname: "Lim"},
  {firstname: "Kevin ", name: "Hauntzer", lastname: "Yarnell"},
  {firstname: "Dennis", name: "Svenskeren", lastname: "Johnsen"},
  {firstname: "Soren", name: "Bjergsen", lastname: "Bjerg"},
  {firstname: "Jason", name: "WildTurtle", lastname: "Tran"},
  {firstname: "Vincent", name: "Biofrost", lastname: "Wang"},
  {firstname: "Parth ", name: "Parth", lastname: "Naidu"}
])
Region.create!([
  {name: "NA LCS", slug: "na-lcs", logo: "http://i.imgur.com/bLqI1ae.png", active: true},
  {name: "EU LCS", slug: "eu-lcs", logo: "http://i.imgur.com/bwoxM82.png", active: true}
])
Role.create!([
  {name: "Top", order: 0},
  {name: "Jungle", order: 1},
  {name: "Mid", order: 2},
  {name: "Bot", order: 3},
  {name: "Support", order: 4},
  {name: "Sub", order: 5},
  {name: "Coach", order: 6}
])
Team.create!([
  {name: "Team SoloMid", abbreviation: "TSM", logo_url: "http://i.imgur.com/O5bpx1K.png", color: "C0C0C0", region_id: 1},
  {name: "Cloud9", abbreviation: "C9", logo_url: "http://i.imgur.com/yORfetB.png", color: "459fd3", region_id: 1},
  {name: "Cloud9 Challenger", abbreviation: "C9C", logo_url: "http://i.imgur.com/yORfetB.png", color: "459fd3", region_id: 1},
  {name: "Counter Logic Gaming", abbreviation: "CLG", logo_url: "http://i.imgur.com/lUv5WSR.png", color: "00b5e2", region_id: 1},
  {name: "Echo Fox", abbreviation: "FOX", logo_url: "http://i.imgur.com/vHBcOj8.png", color: "ff8c26", region_id: 1},
  {name: "Immortals", abbreviation: "IMT", logo_url: "http://i.imgur.com/3StAMJK.png", color: "01b2aa", region_id: 1},
  {name: "Phoenix1", abbreviation: "P1", logo_url: "http://i.imgur.com/iDB8aLX.png", color: "f99c01", region_id: 1},
  {name: "Team Dignitas", abbreviation: "DIG", logo_url: "http://i.imgur.com/EwvAbpx.png", color: "FAC700", region_id: 1},
  {name: "Team EnVyUs", abbreviation: "NV", logo_url: "http://i.imgur.com/ZC3OeHz.png", color: "0078e7", region_id: 1},
  {name: "Team Liquid", abbreviation: "TL", logo_url: "http://i.imgur.com/YKvX8F8.png", color: "7CBAE6", region_id: 1}
])
Transaction.create!([
  {player_id: 1, team_id: 2, date: "2016-05-09", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 2, team_id: 2, date: "2016-05-09", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 3, team_id: 2, date: "2015-05-08", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 4, team_id: 2, date: "2013-05-23", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 5, team_id: 2, date: "2016-05-18", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 6, team_id: 2, date: "2016-05-15", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 7, team_id: 3, date: "2016-04-22", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 8, team_id: 3, date: "2016-04-22", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 9, team_id: 3, date: "2016-04-22", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 10, team_id: 3, date: "2016-04-22", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 11, team_id: 4, date: "2014-11-07", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 12, team_id: 4, date: "2014-12-08", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 13, team_id: 4, date: "2015-10-23", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 14, team_id: 4, date: "2016-01-06", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 15, team_id: 4, date: "2014-01-01", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 16, team_id: 4, date: "2015-11-11", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 17, team_id: 5, date: "2016-12-01", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 18, team_id: 5, date: "2016-01-05", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 19, team_id: 5, date: "2016-01-05", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 20, team_id: 5, date: "2016-06-29", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 21, team_id: 6, date: "2016-12-09", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 22, team_id: 6, date: "2016-12-07", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 23, team_id: 6, date: "2015-12-08", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 24, team_id: 6, date: "2016-12-08", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 25, team_id: 6, date: "2016-11-16", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 26, team_id: 7, date: "2016-05-26", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 27, team_id: 7, date: "2016-05-26", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 28, team_id: 7, date: "2016-12-07", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 29, team_id: 7, date: "2016-12-07", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 30, team_id: 7, date: "2016-11-22", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 31, team_id: 7, date: "2016-12-07", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 32, team_id: 8, date: "2016-09-26", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 33, team_id: 8, date: "2016-09-26", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 34, team_id: 8, date: "2016-09-26", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 35, team_id: 9, date: "2016-05-18", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 37, team_id: 9, date: "2016-05-18", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 39, team_id: 9, date: "2016-05-18", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 36, team_id: 9, date: "2016-05-23", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 38, team_id: 9, date: "2016-05-23", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 40, team_id: 9, date: "2016-06-03", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 41, team_id: 10, date: "2016-01-04", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 42, team_id: 10, date: "2016-12-09", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 43, team_id: 10, date: "2016-01-17", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 44, team_id: 10, date: "2016-09-28", role_id: 7, transtype_id: 1, source: nil},
  {player_id: 45, team_id: 1, date: "2015-11-14", role_id: 1, transtype_id: 1, source: nil},
  {player_id: 46, team_id: 1, date: "2015-11-08", role_id: 2, transtype_id: 1, source: nil},
  {player_id: 47, team_id: 1, date: "2013-11-02", role_id: 3, transtype_id: 1, source: nil},
  {player_id: 48, team_id: 1, date: "2016-12-07", role_id: 4, transtype_id: 1, source: nil},
  {player_id: 49, team_id: 1, date: "2016-05-18", role_id: 5, transtype_id: 1, source: nil},
  {player_id: 50, team_id: 1, date: "2016-02-16", role_id: 7, transtype_id: 1, source: nil}
])
Transtype.create!([
  {name: "Join"},
  {name: "Leave"}
])
